### ISSUE TITLE
misspelled "sing Docker"

### ISSUE THREAD

**Issue by tushar-im** [anthonycepeda/fastapi-sqlmodel-boilerplate#17]
Found a typo there in ReadMe "Using Docker" misspelled as "sing Docker"

**Comment by anthonycepeda** [comment]
Thanks mate! 
Fixed 🤗

**Comment by anthonycepeda** [comment]
> Found a typo there in ReadMe "Using Docker" misspelled as "sing Docker"

Thanks mate! 
Fixed 🤗
