### ISSUE TITLE
Many to Many Models

### ISSUE THREAD

**Issue by res234** [anthonycepeda/fastapi-sqlmodel-boilerplate#3]
I love how you structured this. Would it be possible to add an example of many to many models? I'm having a difficult time getting them to work with your structure. The issue here is if you had a many to many model with heroes (going off the example from the SQL Model docs) you'd need to make a link table in the `public/hero/models.py` file. But what would the `HeroCreate` model look like? And what additional routes would you add in the `routes.py` file? Thank you so much!

**Comment by anthonycepeda** [comment]
Hey,
Thanks for the feedback. I'll check it and get back to you asap.
Thanks

**Comment by res234** [comment]
No rush! Thanks so much for looking into it

**Comment by hrehfeld** [comment]
Any progress on this? I'm also pondering what the cleanest way to use n:m relationships is.

**Comment by anthonycepeda** [comment]
Hi,

Just added the many to many relationship: https://github.com/anthonycepeda/fastapi-sqlmodel/pull/9

```json
{
    "name": "Z-Force",
    "headquarters": "Sister Margaret’s Bar",
    "id": 1,
    "heroes": [
      {
        "secret_name": "Dive Wilson",
        "age": 24,
        "name": "Deadpond",
        "id": 1
      },
      {
        "secret_name": "John Goodman",
        "age": 30,
        "name": "Super-Good-Boy",
        "id": 2
      }
    ]
  }
```

Thanks
