### ISSUE TITLE
Typo in on_startup()?

### ISSUE THREAD

**Issue by sidmitra** [anthonycepeda/fastapi-sqlmodel-boilerplate#4]
I believe the function is not called [here](https://github.com/anthonycepeda/fastapi-sqlmodel/blob/main/api/app.py#L18)? 

```python
 @app.on_event("startup")
    def on_starup():
        create_db_and_tables  # should be create_db_and_tables()
```

**Comment by sidmitra** [comment]
Ancillary issue, is it possible to add how to do migrations say with alembic?

**Comment by anthonycepeda** [comment]
Hi Sidmitra.
In my case, DB modifications are done automatically out of the box wiht SQLModel every time you do changes on your models and re-run the app.

[Here](https://stackoverflow.com/questions/68932099/how-to-get-alembic-to-recognise-sqlmodel-database-model) is an example, in case you'd like to add actual alembic migrations

**Comment by anthonycepeda** [comment]
Hello @sidmitra 
Thanks for the heads up.
I've pushed the fix: https://github.com/anthonycepeda/fastapi-sqlmodel/pull/7
