### ISSUE TITLE
A question for the overall structure

### ISSUE THREAD

**Issue by AdityaLakkad** [anthonycepeda/fastapi-sqlmodel-boilerplate#5]
A newbie here! Why do we put the functions for accessing data into the crud file and later call it in view files, usually I get answers like "to increase security" for this kind of question, but no one is able to explain it, can you please answer that. Thank you.

**Comment by anthonycepeda** [comment]
Hello @AdityaLakkad 

To me its even simpler than for security purposes. When you write code, you wanted to be maintainable, scalable an easy to read for you and others. The best way to achieve that its by sticking to standards. The CRUD approach its one of those standards regarding API's.

Thanks
