### ISSUE TITLE
Problem creating database and tables with "starup" event with fastapi and sqlmodel

### ISSUE THREAD

**Issue by andresprogramacion123** [anthonycepeda/fastapi-sqlmodel-boilerplate#8]
Hi man, I'm working with fastapi and sqlmodel to develop a rest api.
Observing your way of working I see that to create the database you have to execute the created_db.py module.
Looking at the official sqlmodel page they propose to create the database and tables using the "starup" event provided by fastapi.
(attached link https://sqlmodel.tiangolo.com/tutorial/fastapi/simple-hero-api/#create-database-and-tables-on-startup)
In this way, when executing the app with the command "uvicoirn main:app --reload" the database and tables are immediately created.
I tried to do it, but it generates an error, precisely because of the "starup" event. The shell tells me that this event (which apparently comes from starlette) needs other arguments.
I appreciate any help.
![Captura desde 2023-01-24 11-29-51](https://user-images.githubusercontent.com/52362114/214354008-1e3f29c0-51a7-4864-897b-702ceafb79a1.png)
![Captura desde 2023-01-24 11-36-33](https://user-images.githubusercontent.com/52362114/214354040-f58a2f02-f027-4465-bece-3ceaa5cccf56.png)

**Comment by anthonycepeda** [comment]
Hi @andresprogramacion123,

Try without the async on the startup function.

Thanks

**Comment by anthonycepeda** [comment]
I’ve reproduced the issue and it solved not using async on startup function
